### ISSUE TITLE
[pybatsim] Easy scheduler is overlaping jobs

### ISSUE THREAD

**Issue by mickours** [oar-team/batsim#14] opened 2017-01-11 17:05 UTC
I dont know if it is directly related to pybatsim but I have overlapping jobs using Easy and EasyNotopo schedulers of pybatsim. It sometimes give a 200% utilisation for a short time.
Just run the example from the readme: https://github.com/oar-team/batsim#run-batsim-example
but change the ``fillerSched`` by  ``easyBackfillNotopo`` or ``easyBackfill``.

**Comment by mpoquet** [comment] 2017-01-11 18:00
Cannot reproduce the issue. Added pybatsim_tests in c9542e1c3f but they seem to pass (https://gitlab.inria.fr/batsim/batsim/pipelines/403).
Batsim is supposed to halt if the same resource is used by several jobs at the same time (unless time-sharing is enabled). Furthermore, I don't see any overlapping when I visualise the execution traces, what workload are you using?
[easyNOTOPO_medium.pdf](https://github.com/oar-team/batsim/files/699667/easyNOTOPO_medium.pdf)
[easyNOTOPO_tiny.pdf](https://github.com/oar-team/batsim/files/699669/easyNOTOPO_tiny.pdf)
[easy_medium.pdf](https://github.com/oar-team/batsim/files/699668/easy_medium.pdf)
[easy_tiny.pdf](https://github.com/oar-team/batsim/files/699670/easy_tiny.pdf)

**Comment by mickours** [comment] 2017-01-12 10:40
In fact there, with a closer look on the data, I found the problem: Sometimes the job finish time and the next job begin time is exactly the same because the scheduler has no scheduling delay.

I tried to patch the code to add some scheduling delay but I have some assert errors...
I will see with @glesserd if he can help me on this.

**Comment by mpoquet** [comment] 2017-01-26 14:11
The issue seems to be more related to a data analysis issue than a Batsim one, closing it.

**Closed as completed by mpoquet** 2017-01-26 14:11 UTC
